export const GAME_ROOM_JOIN_FAILED_CLOSED =
    '#CSO2_POPUP_ROOM_JOIN_FAILED_CLOSED'
export const GAME_ROOM_JOIN_FAILED_FULL = '#CSO2_POPUP_ROOM_JOIN_FAILED_FULL'
export const GAME_ROOM_JOIN_FAILED_BAD_PASSWORD =
    '#CSO2_POPUP_ROOM_JOIN_FAILED_INVALID_PASSWD'
export const GAME_ROOM_CHANGETEAM_FAILED = '#CSO2_POPUP_ROOM_CHANGETEAM_FAILED'
export const GAME_ROOM_COUNTDOWN_FAILED_NOENEMIES =
    '#CSO2_UI_ROOM_COUNTDOWN_FAILED_NOENEMY'
export const GAME_LOGIN_BAD_USERNAME = '#CSO2_LoginAuth_Certify_NoPassport'
export const GAME_LOGIN_BAD_PASSWORD = '#CSO2_LoginAuth_WrongPassword'
export const GAME_LOGIN_INVALID_USERINFO =
    '#CSO2_ServerMessage_INVALID_USERINFO'
