#%RAML 1.0 DataType

description: The data used when requesting the creation of a new user.
properties:
  username: 
    type: string
    description: The target user's name
    example: "gamer"
  playername: 
    type: string
    description: The target user's ingame name
    example: "VeryGoodGamer"
  password:
    type: string
    description: The target user's secret password
    example: "123456"