#%RAML 1.0 DataType

description: An inventory item.
properties:
  item_id:
    type: integer
    description: The item's ID number
    example: 10003
  ammount:
    type: integer
    description: The ammount of an item
    minimum: 1
    example: 2