#%RAML 1.0 DataType

description: An user's inventory buy menu details.
properties: 
  owner_id:
    type: integer
    description: The owning user's ID
    example: 357
  pistols?: 
    type: integer[]
    description: The user's pistols buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  shotguns?: 
    type: integer[]
    description: The user's shotguns buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  smgs?: 
    type: integer[]
    description: The user's SMGs buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  rifles?: 
    type: integer[]
    description: The user's rifles buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  snipers?: 
    type: integer[]
    description: The user's snipers buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  machineguns?: 
    type: integer[]
    description: The user's machine guns buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  melees?: 
    type: integer[]
    description: The user's melees buy sub menu
    example:
      - 10004
      - 10010
      - 10065
  equipment?: 
    type: integer[]
    description: The user's equipment buy sub menu
    example:
      - 10004
      - 10010
      - 10065
