#%RAML 1.0 DataType

description: An user's equipped cosmetics.
properties:
  owner_id:
    type: integer
    description: The owning user's ID
    example: 25
  ct_item:
    type: integer
    description: The loadout's CT character item ID
    example: 10234
  ter_item:
    type: integer
    description: The loadout's Terrorist character item ID
    example: 10235
  head_item:
    type: integer
    description: The loadout's head wearable item ID
    example: 10240
  glove_item:
    type: integer
    description: The loadout's glove wearable item ID
    example: 10250
  back_item:
    type: integer
    description: The loadout's backpack wearable item ID
    example: 10260
  steps_item:
    type: integer
    description: The loadout's footsteps item ID
    example: 10270
  card_item:
    type: integer
    description: The loadout's card item ID
    example: 10280
  spray_item:
    type: integer
    description: The loadout's spray item ID
    example: 10290